export const conditions = [
  "New",
  "Used",
  "Open-box",
  "Refurbished - Grade A",
  "Refurbished - Grade B",
  "Refurbished - Grade C",
  "Refurbished - Mixed Grade",
  "For Parts",
];

export const categories = [
  "Computer Accessories",
  "Computer Parts",
  "Consumer Electronics",
  "Desktops",
  "Drives and Storage",
  "Laptops",
  "Medical Equipment",
  "Mobile Devices",
  "Monitors",
  "Networking and Telecom",
  "POS Equipment",
  "Printers, Ink, Toner, Parts",
  "Scrap",
  "Servers",
  "Solar Panels",
  "Televisions",
  "Wholesale Goods",
];

export const subcategories = {
  "Computer Accessories": [
    "Keyboards",
    "Mice",
    "Headsets",
    "Webcams",
    "Mouse Pads",
    "Laptop Stands",
    "Bags & Cases",
    "Chargers",
    "Adapters",
  ],
  "Computer Parts": [
    "CPUs",
    "Motherboards",
    "Memory (RAM)",
    "Graphics Cards",
    "Power Supplies",
    "Cases",
    "Cooling",
    "Cables",
    "Batteries",
  ],
  "Consumer Electronics": [
    "Smart Watches",
    "Smart Home Devices",
    "Cameras",
    "Audio Equipment",
  ],
  Desktops: [
    "Gaming Desktops",
    "All-in-One Desktops",
    "Business Desktops",
    "Mini PCs",
  ],
  "Drives and Storage": [
    "Hard Disk Drives (HDD)",
    "Solid State Drives (SSD)",
    "External Drives",
    "Flash Drives",
    "Memory Cards",
  ],
  Laptops: [
    "Gaming Laptops",
    "Ultrabooks",
    "Business Laptops",
    "Convertible Laptops",
  ],
  "Medical Equipment": [
    "Diagnostic Equipment",
    "Monitoring Equipment",
    "Therapeutic Equipment",
  ],
  "Mobile Devices": ["Smartphones", "Tablets", "E-Readers"],
  Monitors: [
    "Gaming Monitors",
    "Professional Monitors",
    "4K Monitors",
    "Ultrawide Monitors",
  ],
  "Networking and Telecom": [
    "Routers",
    "Switches",
    "Modems",
    "Network Adapters",
    "Access Points",
    "Network Attached Storage (NAS)",
  ],
  "POS Equipment": [
    "Cash Registers",
    "Barcode Scanners",
    "Receipt Printers",
    "POS Terminals",
  ],
  "Printers, Ink, Toner, Parts": [
    "Printers",
    "Ink Cartridges",
    "Toner Cartridges",
    "Printer Parts",
  ],
  Scrap: ["Electronic Waste", "Recyclable Materials"],
  Servers: ["Rack Servers", "Tower Servers", "Server Components"],
  "Solar Panels": ["Residential Solar", "Commercial Solar", "Portable Solar"],
  Televisions: ["LED TVs", "OLED TVs", "Smart TVs", "4K TVs"],
  "Wholesale Goods": ["Bulk Computers", "Bulk Accessories", "Bulk Electronics"],
};

export const tradeType = {
  Buy: "Want to Buy",
  Sell: "Want to Sell",
};

export const manufacturers = [
  "Mixed Lots",
  "Apple",
  "Cisco Systems",
  "Oracle Corporation (Sun Microsystem)",
  "Dell",
  "Dell EMC",
  "Fujitsu",
  "Google",
  "HP",
  "HPE",
  "IBM",
  "Intel",
  "Lenovo",
  "Samsung",
  "Toshiba",
];

export const screenSizes = [
  "11.6 Inch",
  "12.3 Inch",
  "13.3 Inch",
  "14 Inch",
  "15.6 Inch",
  "17.3 Inch",
  "19 Inch",
  "24 Inch",
  "32 Inch",
  "40 Inch",
  "55 Inch",
  "65 Inch",
  "75 Inch",
  "85 Inch",
  "100 Inch",
];

export const screenTypes = ["LCD", "LED", "OLED", "Plasma", "CRT"];

export const processors = [
  "Intel Core i3",
  "Intel Core i5",
  "Intel Core i7",
  "Intel Core i9",
  "AMD Ryzen 3",
  "AMD Ryzen 5",
  "AMD Ryzen 7",
  "AMD Ryzen 9",
  "Apple M1",
  "Apple M2",
  "Apple M3",
  "Qualcomm Snapdragon",
];

export const processorGenerations = [
  "1st Generation",
  "2nd Generation",
  "3rd Generation",
  "4th Generation",
  "5th Generation",
  "6th Generation",
  "7th Generation",
  "8th Generation",
  "9th Generation",
  "10th Generation",
  "11th Generation",
  "12th Generation",
  "13th Generation",
  "14th Generation",
  "15th Generation",
  "16th Generation",
  "Ryzen 1000 Series",
  "Ryzen 2000 Series",
  "Ryzen 3000 Series",
  "Ryzen 4000 Series",
  "Ryzen 5000 Series",
  "Ryzen 6000 Series",
  "Ryzen 7000 Series",
  "Apple M1",
  "Apple M2",
  "Apple M3",
  "Snapdragon 600 Series",
  "Snapdragon 700 Series",
  "Snapdragon 800 Series",
  "Exynos 7000 Series",
  "Exynos 8000 Series",
  "Helio G Series",
  "Helio P Series",
  "Helio X Series",
  "Cortex A Series",
  "Cortex R Series",
  "Cortex M Series",
  "Power9",
  "Power10",
];

export const graphicMemory = [
  "2GB",
  "4GB",
  "6GB",
  "8GB",
  "10GB",
  "12GB",
  "16GB",
  "20GB",
  "24GB",
  "32GB",
];

export const ramSizes = [
  "2GB",
  "4GB",
  "6GB",
  "8GB",
  "10GB",
  "12GB",
  "16GB",
  "20GB",
  "24GB",
  "32GB",
  "40GB",
  "48GB",
  "56GB",
  "64GB",
  "72GB",
  "80GB",
  "88GB",
  "96GB",
  "104GB",
  "112GB",
  "120GB",
  "128GB",
  "128GB+",
];

export const storageTypes = [
  "Hard Disk Drive (HDD)",
  "Solid State Drive (SSD)",
  "NVMe SSD",
  "eMMC Flash Storage",
  "Hybrid Drive",
  "Intel Optane Memory",
];

export const storageSizes = [
  "128GB",
  "256GB",
  "512GB",
  "1TB",
  "2TB",
  "4TB",
  "8TB",
  "16TB",
  "32TB",
];

export const countries = [
  "United States",
  "Canada",
  "United Kingdom",
  "France",
  "Germany",
  "Italy",
  "Spain",
  "Australia",
  "Brazil",
  "China",
  "India",
  "Japan",
  "Russia",
  "South Africa",
  "Mexico",
  "Argentina",
  "Egypt",
  "Saudi Arabia",
  "Nigeria",
  "Kenya",
];
